BEGIN;


CREATE TABLE IF NOT EXISTS public.antropometria
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_coorte bigint NOT NULL,
    massa real NOT NULL,
    estatura real NOT NULL,
    esp_polegar real NOT NULL,
    quadril real NOT NULL,
    abdomen real NOT NULL,
    antebraco_dir real NOT NULL,
    antebraco_esq real NOT NULL,
    braco_rel_dir real NOT NULL,
    braco_rel_esq real NOT NULL,
    braco_ctr_dir real NOT NULL,
    braco_ctr_esq real NOT NULL,
    panturrilha_dir real NOT NULL,
    panturrilha_esq real NOT NULL,
    coxa_sup_dir real NOT NULL,
    coxa_sup_esq real NOT NULL,
    CONSTRAINT antropometria_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.apoio_familiar_social
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_vida_saude bigint NOT NULL,
    cuidador text COLLATE pg_catalog."default" NOT NULL,
    idade_cuidador smallint NOT NULL,
    sexo_cuidador text COLLATE pg_catalog."default" NOT NULL,
    servico_saude text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT apoio_familiar_social_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.apoio_familiar_social
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.composicao_familiar
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_vida_saude bigint NOT NULL,
    modo_vida text COLLATE pg_catalog."default" NOT NULL,
    satisf_vida text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT composicao_familiar_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.composicao_familiar
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.condicao_saude
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_vida_saude smallint NOT NULL,
    medicamentos text COLLATE pg_catalog."default" NOT NULL,
    motivo_uso text COLLATE pg_catalog."default" NOT NULL,
    aquisicao text COLLATE pg_catalog."default" NOT NULL,
    saude_geral text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT condicao_saude_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.condicao_saude
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.entrevistado
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome_entrevistado text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT entrevistado_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.estudo_alimentacao
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_entrevistado bigint NOT NULL,
    id_usuario bigint NOT NULL,
    data date NOT NULL,
    horario time without time zone NOT NULL,
    CONSTRAINT estudo_alimentacao_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.estudo_alimentacao
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.estudo_ansiedade
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_entrevistado bigint NOT NULL,
    id_usuario bigint NOT NULL,
    data date NOT NULL,
    horario time without time zone NOT NULL,
    CONSTRAINT estudo_ansiedade_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.estudo_ansiedade
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.estudo_atividade_fisica
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_entrevistado bigint NOT NULL,
    id_usuario bigint NOT NULL,
    data date NOT NULL,
    horario time without time zone NOT NULL,
    CONSTRAINT estudo_atividade_fisica_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.estudo_atividade_fisica
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.estudo_coorte
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_entrevistado bigint NOT NULL,
    id_usuario bigint NOT NULL,
    data date NOT NULL,
    horario time without time zone NOT NULL,
    CONSTRAINT estudo_coorte_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.estudo_qualidade_vida
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_entrevistado bigint NOT NULL,
    id_usuario bigint NOT NULL,
    data date NOT NULL,
    horario time without time zone NOT NULL,
    CONSTRAINT estudo_qualidade_vida_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.estudo_qualidade_vida
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.estudo_sarcopenia
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_entrevistado bigint NOT NULL,
    id_usuario bigint NOT NULL,
    data date NOT NULL,
    horario time without time zone NOT NULL,
    CONSTRAINT estudo_sarcopenia_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.estudo_sarcopenia
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.estudo_vida_saude
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_entrevistado bigint NOT NULL,
    id_usuario bigint NOT NULL,
    data date NOT NULL,
    horario time without time zone NOT NULL,
    CONSTRAINT estudo_vida_saude_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.estudo_vida_saude
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.info_pessoais
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_vida_saude bigint NOT NULL,
    data_nasc date NOT NULL,
    sexo text COLLATE pg_catalog."default" NOT NULL,
    pele text COLLATE pg_catalog."default" NOT NULL,
    local_nasc date NOT NULL,
    cidade text COLLATE pg_catalog."default" NOT NULL,
    estado text COLLATE pg_catalog."default" NOT NULL,
    pais text COLLATE pg_catalog."default" NOT NULL,
    local_resid text COLLATE pg_catalog."default" NOT NULL,
    tempo_resid smallint NOT NULL,
    estado_civil text COLLATE pg_catalog."default" NOT NULL,
    anos_estudo smallint NOT NULL,
    nivel_alfab text COLLATE pg_catalog."default" NOT NULL,
    aposentadoria text COLLATE pg_catalog."default" NOT NULL,
    valor_apos integer NOT NULL,
    CONSTRAINT info_pessoais_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.info_pessoais
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.moradia
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_vida_saude bigint NOT NULL,
    casa text COLLATE pg_catalog."default" NOT NULL,
    esgoto text COLLATE pg_catalog."default" NOT NULL,
    luz text COLLATE pg_catalog."default" NOT NULL,
    lixo text COLLATE pg_catalog."default" NOT NULL,
    meios_transporte text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT moradia_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.moradia
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.perguntas_alimentacao
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_alimentacao bigint NOT NULL,
    qtd_frutas text COLLATE pg_catalog."default" NOT NULL,
    qtd_verduras text COLLATE pg_catalog."default" NOT NULL,
    qtd_leguminosas text COLLATE pg_catalog."default" NOT NULL,
    qtd_carbo smallint NOT NULL,
    qtd_pao smallint NOT NULL,
    qtd_bolo smallint NOT NULL,
    qtd_bolacha smallint NOT NULL,
    qtd_carnes text COLLATE pg_catalog."default" NOT NULL,
    gordura_carne text COLLATE pg_catalog."default" NOT NULL,
    qtd_peixes text COLLATE pg_catalog."default" NOT NULL,
    "qtd_ laticinios" text COLLATE pg_catalog."default" NOT NULL,
    tipo_laticinios text COLLATE pg_catalog."default" NOT NULL,
    qtd_processados text COLLATE pg_catalog."default" NOT NULL,
    qtd_doces text COLLATE pg_catalog."default" NOT NULL,
    tipo_gordura text COLLATE pg_catalog."default" NOT NULL,
    sal text COLLATE pg_catalog."default" NOT NULL,
    qtd_agua text COLLATE pg_catalog."default" NOT NULL,
    qtd_alcool text COLLATE pg_catalog."default" NOT NULL,
    atv_fisica text COLLATE pg_catalog."default" NOT NULL,
    info_nutri text COLLATE pg_catalog."default" NOT NULL,
    cafe_manha text COLLATE pg_catalog."default" NOT NULL,
    lanche_manha text COLLATE pg_catalog."default" NOT NULL,
    almoco text COLLATE pg_catalog."default" NOT NULL,
    lanche_tarde text COLLATE pg_catalog."default" NOT NULL,
    jantar text COLLATE pg_catalog."default" NOT NULL,
    lanche_noite text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT perguntas_alimentacao_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.perguntas_alimentacao
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.perguntas_ansiedade
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_estudo_ansiedade bigint NOT NULL,
    p1 text COLLATE pg_catalog."default" NOT NULL,
    p2 text COLLATE pg_catalog."default" NOT NULL,
    p3 text COLLATE pg_catalog."default" NOT NULL,
    p4 text COLLATE pg_catalog."default" NOT NULL,
    p5 text COLLATE pg_catalog."default" NOT NULL,
    p6 text COLLATE pg_catalog."default" NOT NULL,
    p7 text COLLATE pg_catalog."default" NOT NULL,
    p8 text COLLATE pg_catalog."default" NOT NULL,
    p9 text COLLATE pg_catalog."default" NOT NULL,
    p10 text COLLATE pg_catalog."default" NOT NULL,
    p11 text COLLATE pg_catalog."default" NOT NULL,
    p12 text COLLATE pg_catalog."default" NOT NULL,
    p13 text COLLATE pg_catalog."default" NOT NULL,
    p14 text COLLATE pg_catalog."default" NOT NULL,
    p15 text COLLATE pg_catalog."default" NOT NULL,
    p16 text COLLATE pg_catalog."default" NOT NULL,
    p17 text COLLATE pg_catalog."default" NOT NULL,
    p18 text COLLATE pg_catalog."default" NOT NULL,
    p19 text COLLATE pg_catalog."default" NOT NULL,
    p20 text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT perguntas_ansiedade_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.perguntas_ansiedade
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.perguntas_atv_fisica
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_atv_fisica bigint NOT NULL,
    caminhada smallint NOT NULL,
    tc time without time zone NOT NULL,
    atv_moderada smallint NOT NULL,
    t_atv_mod time without time zone NOT NULL,
    atv_vigorosa smallint NOT NULL,
    t_atv_vig time without time zone NOT NULL,
    ts_semana time without time zone NOT NULL,
    ts_fim_sem time without time zone NOT NULL,
    CONSTRAINT perguntas_atv_fisica_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.perguntas_atv_fisica
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.perguntas_sarcopenia
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_estudo_sarcopenia bigint NOT NULL,
    forca text COLLATE pg_catalog."default" NOT NULL,
    apoio_marcha text COLLATE pg_catalog."default" NOT NULL,
    levantar_cadeira text COLLATE pg_catalog."default" NOT NULL,
    subir_escada text COLLATE pg_catalog."default" NOT NULL,
    quedas text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT perguntas_sarcopenia_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.perguntas_sarcopenia
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.problemas_saude
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_vida_saude bigint NOT NULL,
    reumatismo text COLLATE pg_catalog."default" NOT NULL,
    asma_bronquite text COLLATE pg_catalog."default" NOT NULL,
    pressao_alta text COLLATE pg_catalog."default" NOT NULL,
    varizes text COLLATE pg_catalog."default" NOT NULL,
    diabetes text COLLATE pg_catalog."default" NOT NULL,
    obesidade text COLLATE pg_catalog."default" NOT NULL,
    derrame text COLLATE pg_catalog."default" NOT NULL,
    incontinencia text COLLATE pg_catalog."default" NOT NULL,
    prisao_ventre text COLLATE pg_catalog."default" NOT NULL,
    insonia text COLLATE pg_catalog."default" NOT NULL,
    catarata text COLLATE pg_catalog."default" NOT NULL,
    problema_coluna text COLLATE pg_catalog."default" NOT NULL,
    artrite_artrose text COLLATE pg_catalog."default" NOT NULL,
    osteoporose text COLLATE pg_catalog."default" NOT NULL,
    nervos text COLLATE pg_catalog."default" NOT NULL,
    tuberculose text COLLATE pg_catalog."default" NOT NULL,
    cardiaco text COLLATE pg_catalog."default" NOT NULL,
    anemia text COLLATE pg_catalog."default" NOT NULL,
    parkinson text COLLATE pg_catalog."default" NOT NULL,
    cancer text COLLATE pg_catalog."default" NOT NULL,
    alzheimer text COLLATE pg_catalog."default" NOT NULL,
    depressao text COLLATE pg_catalog."default" NOT NULL,
    osteomioarticulares text COLLATE pg_catalog."default" NOT NULL,
    tontura text COLLATE pg_catalog."default" NOT NULL,
    colesterol text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT problemas_saude_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.problemas_saude
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.qld_vida_emocional
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_qld_vida bigint NOT NULL,
    tempo_atv text COLLATE pg_catalog."default" NOT NULL,
    qtd_atividade text COLLATE pg_catalog."default" NOT NULL,
    cuidado_atv text COLLATE pg_catalog."default" NOT NULL,
    vigor text COLLATE pg_catalog."default" NOT NULL,
    nervoso text COLLATE pg_catalog."default" NOT NULL,
    deprimido text COLLATE pg_catalog."default" NOT NULL,
    calmo text COLLATE pg_catalog."default" NOT NULL,
    energia text COLLATE pg_catalog."default" NOT NULL,
    desanimado text COLLATE pg_catalog."default" NOT NULL,
    esgotado text COLLATE pg_catalog."default" NOT NULL,
    feliz text COLLATE pg_catalog."default" NOT NULL,
    cansado text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT qld_vida_emocional_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.qld_vida_emocional
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.qld_vida_fisica
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_qld_vida bigint NOT NULL,
    atv_rigorosa text COLLATE pg_catalog."default" NOT NULL,
    atv_moderada text COLLATE pg_catalog."default" NOT NULL,
    carregar_mant text COLLATE pg_catalog."default" NOT NULL,
    subir_lance text COLLATE pg_catalog."default" NOT NULL,
    subir_escada text COLLATE pg_catalog."default" NOT NULL,
    flexionar text COLLATE pg_catalog."default" NOT NULL,
    andar_1km text COLLATE pg_catalog."default" NOT NULL,
    andar_quart text COLLATE pg_catalog."default" NOT NULL,
    andar_vq text COLLATE pg_catalog."default" NOT NULL,
    banho text COLLATE pg_catalog."default" NOT NULL,
    tempo_atv text COLLATE pg_catalog."default" NOT NULL,
    qtd_atividades text COLLATE pg_catalog."default" NOT NULL,
    limitacao_atv text COLLATE pg_catalog."default" NOT NULL,
    dificuldade_atv text COLLATE pg_catalog."default" NOT NULL,
    dor_corpo text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT qld_vida_fisica_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.qld_vida_fisica
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.qld_vida_geral
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_qld_vida bigint NOT NULL,
    saude_geral text COLLATE pg_catalog."default" NOT NULL,
    saude_ano text COLLATE pg_catalog."default" NOT NULL,
    atv_social text COLLATE pg_catalog."default" NOT NULL,
    t_atv_social text COLLATE pg_catalog."default" NOT NULL,
    obediencia text COLLATE pg_catalog."default" NOT NULL,
    saude_comp text COLLATE pg_catalog."default" NOT NULL,
    saude_piorar text COLLATE pg_catalog."default" NOT NULL,
    saude_ex text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT qld_vida_geral_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.qld_vida_geral
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.sinais_vitais
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_coorte bigint NOT NULL,
    pa text COLLATE pg_catalog."default" NOT NULL,
    fc bigint NOT NULL,
    saturacao real NOT NULL,
    CONSTRAINT sinais_vitais_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.testes_motores
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_coorte bigint NOT NULL,
    timed_up_go_1 real NOT NULL,
    timed_up_go_2 real NOT NULL,
    timed_up_go_3 real NOT NULL,
    chair_test smallint NOT NULL,
    pren_man_dir_1 real NOT NULL,
    pren_man_dir_2 real NOT NULL,
    pren_man_dir_3 real NOT NULL,
    pren_man_esq_1 real NOT NULL,
    pren_man_esq_2 real NOT NULL,
    pren_man_esq_3 real NOT NULL,
    CONSTRAINT testes_motores_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome_usuario text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    senha text COLLATE pg_catalog."default" NOT NULL,
    papel text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.usuarios
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.antropometria
    ADD CONSTRAINT antropometria_id_coorte_fkey FOREIGN KEY (id_coorte)
    REFERENCES public.estudo_coorte (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.apoio_familiar_social
    ADD CONSTRAINT apoio_familiar_social_id_vida_saude_fkey FOREIGN KEY (id_vida_saude)
    REFERENCES public.estudo_vida_saude (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.composicao_familiar
    ADD CONSTRAINT composicao_familiar_id_vida_saude_fkey FOREIGN KEY (id_vida_saude)
    REFERENCES public.estudo_vida_saude (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.condicao_saude
    ADD CONSTRAINT condicao_saude_id_vida_saude_fkey FOREIGN KEY (id_vida_saude)
    REFERENCES public.estudo_vida_saude (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudo_alimentacao
    ADD CONSTRAINT estudo_alimentacao_id_entrevistado_fkey FOREIGN KEY (id_entrevistado)
    REFERENCES public.entrevistado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudo_alimentacao
    ADD CONSTRAINT estudo_alimentacao_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudo_ansiedade
    ADD CONSTRAINT estudo_ansiedade_id_entrevistado_fkey FOREIGN KEY (id_entrevistado)
    REFERENCES public.entrevistado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudo_ansiedade
    ADD CONSTRAINT estudo_ansiedade_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudo_atividade_fisica
    ADD CONSTRAINT estudo_atividade_fisica_id_entrevistado_fkey FOREIGN KEY (id_entrevistado)
    REFERENCES public.entrevistado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudo_atividade_fisica
    ADD CONSTRAINT estudo_atividade_fisica_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudo_coorte
    ADD CONSTRAINT estudo_coorte_id_entrevistado_fkey FOREIGN KEY (id_entrevistado)
    REFERENCES public.entrevistado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudo_coorte
    ADD CONSTRAINT estudo_coorte_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudo_qualidade_vida
    ADD CONSTRAINT estudo_qualidade_vida_id_entrevistado_fkey FOREIGN KEY (id_entrevistado)
    REFERENCES public.entrevistado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudo_qualidade_vida
    ADD CONSTRAINT estudo_qualidade_vida_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudo_sarcopenia
    ADD CONSTRAINT estudo_sarcopenia_id_entrevistado_fkey FOREIGN KEY (id_entrevistado)
    REFERENCES public.entrevistado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudo_sarcopenia
    ADD CONSTRAINT estudo_sarcopenia_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudo_vida_saude
    ADD CONSTRAINT estudo_vida_saude_id_entrevistado_fkey FOREIGN KEY (id_entrevistado)
    REFERENCES public.entrevistado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudo_vida_saude
    ADD CONSTRAINT estudo_vida_saude_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.info_pessoais
    ADD CONSTRAINT info_pessoais_id_vida_saude_fkey FOREIGN KEY (id_vida_saude)
    REFERENCES public.estudo_vida_saude (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.moradia
    ADD CONSTRAINT moradia_id_vida_saude_fkey FOREIGN KEY (id_vida_saude)
    REFERENCES public.estudo_vida_saude (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.perguntas_alimentacao
    ADD CONSTRAINT perguntas_alimentacao_id_alimentacao_fkey FOREIGN KEY (id_alimentacao)
    REFERENCES public.estudo_alimentacao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.perguntas_ansiedade
    ADD CONSTRAINT perguntas_ansiedade_id_estudo_ansiedade_fkey FOREIGN KEY (id_estudo_ansiedade)
    REFERENCES public.estudo_ansiedade (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.perguntas_atv_fisica
    ADD CONSTRAINT perguntas_atv_fisica_id_atv_fisica_fkey FOREIGN KEY (id_atv_fisica)
    REFERENCES public.estudo_atividade_fisica (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.perguntas_sarcopenia
    ADD CONSTRAINT perguntas_sarcopenia_id_estudo_sarcopenia_fkey FOREIGN KEY (id_estudo_sarcopenia)
    REFERENCES public.estudo_sarcopenia (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.problemas_saude
    ADD CONSTRAINT problemas_saude_id_vida_saude_fkey FOREIGN KEY (id_vida_saude)
    REFERENCES public.estudo_vida_saude (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.qld_vida_emocional
    ADD CONSTRAINT qld_vida_emocional_id_qld_vida_fkey FOREIGN KEY (id_qld_vida)
    REFERENCES public.estudo_qualidade_vida (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.qld_vida_fisica
    ADD CONSTRAINT qld_vida_fisica_id_qld_vida_fkey FOREIGN KEY (id_qld_vida)
    REFERENCES public.estudo_qualidade_vida (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.qld_vida_geral
    ADD CONSTRAINT qld_vida_geral_id_qld_vida_fkey FOREIGN KEY (id_qld_vida)
    REFERENCES public.estudo_qualidade_vida (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sinais_vitais
    ADD CONSTRAINT sinais_vitais_id_coorte_fkey FOREIGN KEY (id_coorte)
    REFERENCES public.estudo_coorte (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.testes_motores
    ADD CONSTRAINT testes_motores_id_coorte_fkey FOREIGN KEY (id_coorte)
    REFERENCES public.estudo_coorte (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;